# Generated by Django 3.2.10 on 2023-10-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=90, null=True)),
                ('Email', models.EmailField(blank=True, max_length=60, null=True)),
                ('Password', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
