# Generated by Django 3.2.10 on 2023-10-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
